#Config file - Change it according to your data
aa_alignment: "data/raw/aa.fasta"
structural_fasta: "data/raw/structural.fasta"

final_alignment: "data/alignment/final_alignment.fasta"
tree: "data/tree/tree.nwk"
